# Generated by Django 4.1 on 2022-10-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product", name="stock", field=models.IntegerField(),
        ),
    ]
